name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  E2Etest:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Init
      run : cd ${GITHUB_WORKSPACE}

    - name: Build
      run : make

    - name: Initialize plist
      run : make test-init
        
    - name: Run
      run : make test-run
        

